apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mirror-repo
spec:
  serviceName: mirror-repo
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: mirror-repo
  template:
    metadata:
      labels:
        app: mirror-repo
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "ocp-mirror-repo.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mirror-repo
              topologyKey: kubernetes.io/hostname
      containers:
        - name: mirror-repo
          image: '{{ .Values.images.ubi8 }}'
          command:
            - /bin/bash
          args:
            - /scripts-dir/run-mirror-repo.sh
          env:
            - name: RHEL_VERSION
              value: '{{ .Values.pod_envs.RHEL_VERSION }}'
            - name: OPENSHIFT_VERSION
              value: '{{ .Values.pod_envs.OPENSHIFT_VERSION }}'
          volumeMounts:
            {{- if eq .Values.entitlement.type "pod" }}
            - name: rhsm-entitlement
              mountPath: /etc/pki/entitlement
              readOnly: true
            {{- end }}
            - name: scripts-vol
              mountPath: /scripts-dir
              readOnly: true
            - name: mirror-repo
              mountPath: /var/www/html
        - name: apache
          image: '{{ .Values.images.httpd }}'
          volumeMounts:
            - name: mirror-repo
              mountPath: /var/www/html
              readOnly: true
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            exec:
              command:
                - cat
                - /var/www/html/repodata/repomd.xml
      volumes:
        {{- if eq .Values.entitlement.type "pod" }}
        - name: rhsm-entitlement
          secret:
            secretName: rhsm-entitlement
        {{- end }}
        - name: scripts-vol
          configMap:
            name: scripts-mirror-repo
            defaultMode: 420
  volumeClaimTemplates:
    - metadata:
        name: mirror-repo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
